---
- hosts: node
  gather_facts: no
  vars:
    - base_installer: https://gitlab.hds-cloudconnect.com:8443/dcos-install-m210.tar
    - agent_type: slave_public
  tasks:
 
  - name: download node installer
    raw: "sudo wget -O dcos-installer.tar {{ base_installer }} --no-check-certificate"
  
  - name: create folder
    raw: "sudo mkdir -p /opt/dcos_install_tmp"
   
  - name: extract installer
    raw: "sudo tar xf dcos-installer.tar -C /opt/dcos_install_tmp"
    
  - name: configure node
    raw: "sudo bash /opt/dcos_install_tmp/dcos_install.sh {{ agent_type }}"
